version: "3.9"
services:
  rtmp:
    # build: ./rtmp
    image: si3mshady/rmtp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_live_server
    volumes:
      - ./data:/tmp/hls

  auth:
    image: si3mshady/livestream_auth
    # build: ./auth
    container_name: auth_live_server

  streamshady_backend:
    image: si3mshady/streamshady_be:v2
    # build: ./server
    ports:
    - "4000:4000"
    # container_name: videostream_backend

  streamshady_frontend:
    image: si3mshady/streamshady_fe:v2
    # build: ./sav2
    ports:
    - "3000:3000"
    # container_name: videostream_backend